### ISSUE TITLE
Switch to ruff linter

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/movement#71]
Switch from using Black to using ruff, as in https://github.com/mesh-adaptation/goalie/pull/166. Doing so allows us to define all the configuration inside `pyproject.toml`, in line with #68.

**Comment by ddundo** [comment]
@jwallwork23 I'm happy to take this too if you'd like :)

**Comment by jwallwork23** [comment]
> I'm happy to take this too if you'd like :)

Perfect, thanks very much!

**Comment by ddundo** [comment]
Done in #68
