### ISSUE TITLE
Run demos directly during testing

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/movement#81]
Some of the code coverage information is missing because we are running the demos using subprocesses.

Perhaps we could instead run them directly with Pytest and have the Pytest configuration delete any outputs.

**Comment by ddundo** [comment]
Here's what I mentioned during the meeting, to wrap each demo in a test case: https://stackoverflow.com/a/56813896

**Comment by jwallwork23** [comment]
Closed by #108.
