### ISSUE TITLE
Use `sed` instead of `MOVEMENT_REGRESSION_TEST`

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/movement#82]
Rather than confusing the demo content with environment variables, we should apply specific modifications with `sed` when running the test suite.

**Comment by jwallwork23** [comment]
@ddundo would you mind addressing this like you did with https://github.com/mesh-adaptation/animate/issues/111 and https://github.com/mesh-adaptation/goalie/issues/175?

**Comment by ddundo** [comment]
Of course :)

**Comment by jwallwork23** [comment]
Great, thanks!
